#!/usr/bin/env bash
# Description: Generate and set a random hostname on Linux
# Requires: sed
# Usage: set-random-hostname

__set_random_hostname() {

  # set a prefix if you'd like (thx @czerniachowicz)
  local prefix="server_"

  # trim unusable characters if prefixed
  if [ -n "$prefix" ]; then
    prefix="$(echo $prefix | tr -d '\011\012\013\014\015\040')"
  fi

  # add random section
  local new_hostname="${prefix}$(head -n1 < <(fold -w6 < <(tr -cd 'a-z0-9' < /dev/urandom)))"

  # if new hostname is too long, trim to max
  if [[ ${#new_hostname} -gt 64 ]]; then
    new_hostname=${new_hostname:0:64}
  fi

  echo "$new_hostname"
}

__set_random_hostname

